name: sample_app
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"
dependencies:
  ferry: ^0.10.4
  firebase_analytics: ^9.0.4
  firebase_core: ^1.10.6
  firebase_crashlytics: ^2.4.5
  flutter:
    sdk: flutter
  go_router: ^3.0.0
  gql_http_link: ^0.4.0

dev_dependencies:
  build_runner: ^2.1.7
  ferry_generator: ^0.4.0
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  pedantic_mono: any

flutter:
  uses-material-design: true

  assets:
    - assets/images/
